filters:
  - label: ğŸ’ BE
    regexs:
      - /backend|BE|server/
      - /ë°±ì—”ë“œ/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ BugFix
    regexs:
      - /Fix|fix|bugfix|correct/
      - /ì´ìŠˆ|ì˜¤ë¥˜|ë¬¸ì œ|ì—ëŸ¬|ì²˜ë¦¬/
    events: [issues, pull_request]
    targets: [title, body]

  - label: Â ğŸš€Â Deploy
    regexs:
      - /deploy|deployment|CD/
      - /ë°°í¬|ë¨¸ì§€/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ“ƒ Docs
    regexs:
      - /docs|documentation|README/
      - /ë¬¸ì„œ/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ¥ FE
    regexs:
      - /frontend|FE|React|Vue|Angular/
      - /í”„ë¡ íŠ¸/
    events: [issues, pull_request]
    targets: [title, body]

  - label: âœ¨ Feature
    regexs:
      - /Feat|feature|feat|enhancement|new/
      - /ê¸°ëŠ¥|êµ¬í˜„|ê°œë°œ|ì ìš©/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ¨ HTML&CSS
    regexs:
      - /Design|HTML|CSS|styling|layout/
      - /ë””ìì¸/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ”§ Modify
    regexs:
      - /Update|modify|update|change/
      - /ì—…ë°ì´íŠ¸|ë³€ê²½|ì¡°ì •|ì‚­ì œ|ì¶”ê°€/
      - /^(?!.*ì˜¤ë¥˜ ìˆ˜ì •)|ìˆ˜ì •/
      - />|->/
    events: [issues, pull_request]
    targets: [title, body]

  - label: ğŸ™‹â€â™‚ï¸ Question
    regexs:
      - /question|help wanted|inquiry/
      - /ì§ˆë¬¸/
    events: [issues, pull_request]
    targets: [title, body]

  - label: â™»ï¸ Refactor
    regexs:
      - /refactor|code quality|clean up/
      - /ë¦¬íŒ©í† ë§|ë¦¬íŒ©í„°ë§|ì´ë™/
    events: [issues, pull_request]
    targets: [title, body]

  - label: âš™ Setting
    regexs:
      - /setting|config|configuration/
      - /í™˜ê²½|ì„¤ì •/
    events: [issues, pull_request]
    targets: [title, body]

  - label: âœ… Test
    regexs:
      - /Test|test|testing|TDD/
      - /í…ŒìŠ¤íŠ¸/
    events: [issues, pull_request]
    targets: [title, body]
